/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.mds.mongodb;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        MongoClient mongoClient = MongoClients.create(args[0]);
        MongoDatabase database = mongoClient.getDatabase(args[1]);

        System.out.println(database.listCollectionNames());
    }
}
